image: 10.48.51.187:5000/com.inspur/cibase:0.2.1

stages:
  - build
  - release

build backend:
  stage: build
  script:
    - sed -i 's/<\/mirrors>/<mirror> <id>nexus<\/id> <mirrorOf>central<\/mirrorOf> <name>my nexus<\/name> <url>http:\/\/10.48.51.156:8081\/repository\/maven-public\/<\/url><\/mirror><\/mirrors>/g' /usr/share/maven/conf/settings.xml
    - update_pom_version
    - echo $SONAR_URL
    - echo $SONAR_LOGIN
    - >-
        mvn --batch-mode verify sonar:sonar
        -Dsonar.host.url=$SONAR_URL
        -Dsonar.login=admin
        -Dsonar.password=admin
        -Dsonar.gitlab.project_id=$CI_PROJECT_PATH
        -Dsonar.gitlab.commit_sha=$CI_COMMIT_SHA
        -Dsonar.gitlab.ref_name=$CI_COMMIT_REF_NAME
        -Dsonar.analysis.serviceGroup=$GROUP_NAME
        -Dsonar.analysis.commitId=$CI_COMMIT_SHA
        -Dsonar.projectKey=${GROUP_NAME}:${PROJECT_NAME}
    - mvn package -U -DskipTests=true
    - docker_build

release backend:
  stage: release
  script:
    - chart_build

.auto_devops: &auto_devops |
  http_status_code=`curl -o .auto_devops.sh -s -m 10 --connect-timeout 10 -w %{http_code} "${CHOERODON_URL}/devops/ci?token=${Token}&type=microservice"`
  if [ "$http_status_code" != "200" ]; then
    cat .auto_devops.sh
    exit 1
  fi
  source .auto_devops.sh
  function docker_build()
  {
    docker login -u ${DOCKER_USER} -p ${DOCKER_PWD} ${DOCKER_REGISTRY}
    docker build -t ${DOCKER_REGISTRY}/${GROUP_NAME}/${PROJECT_NAME}:${CI_COMMIT_TAG} ${1:-"."}
    docker push ${DOCKER_REGISTRY}/${GROUP_NAME}/${PROJECT_NAME}:${CI_COMMIT_TAG}
  }

before_script:
  - *auto_devops