# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: 10.48.51.113:30002/operation-hjwtest/testng-selenium
  pullPolicy: Always

env: {}

resources:
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources,such as Minikube. If you do want to specify resources,uncomment the following
  # lines,adjust them as necessary,and remove the curly braces after 'resources:'.
  limits:
    # cpu: 100m
    memory: 500Mi
  requests:
    # cpu: 100m
    memory: 256Mi

service:
  type: NodePort
  port: 8999